#pragma once

const std::string installed_fonts = R"(IBMPlex/IBMPlexMono-Bold.ttf
IBMPlex/IBMPlexMono-BoldItalic.ttf
IBMPlex/IBMPlexMono-ExtraLight.ttf
IBMPlex/IBMPlexMono-ExtraLightItalic.ttf
IBMPlex/IBMPlexMono-Italic.ttf
IBMPlex/IBMPlexMono-Light.ttf
IBMPlex/IBMPlexMono-LightItalic.ttf
IBMPlex/IBMPlexMono-Medium.ttf
IBMPlex/IBMPlexMono-MediumItalic.ttf
IBMPlex/IBMPlexMono-Regular.ttf
IBMPlex/IBMPlexMono-SemiBold.ttf
IBMPlex/IBMPlexMono-SemiBoldItalic.ttf
IBMPlex/IBMPlexMono-Thin.ttf
IBMPlex/IBMPlexMono-ThinItalic.ttf
IBMPlex/IBMPlexSans-Bold.ttf
IBMPlex/IBMPlexSans-BoldItalic.ttf
IBMPlex/IBMPlexSans-ExtraLight.ttf
IBMPlex/IBMPlexSans-ExtraLightItalic.ttf
IBMPlex/IBMPlexSans-Italic.ttf
IBMPlex/IBMPlexSans-Light.ttf
IBMPlex/IBMPlexSans-LightItalic.ttf
IBMPlex/IBMPlexSans-Medium.ttf
IBMPlex/IBMPlexSans-MediumItalic.ttf
IBMPlex/IBMPlexSans-Regular.ttf
IBMPlex/IBMPlexSans-SemiBold.ttf
IBMPlex/IBMPlexSans-SemiBoldItalic.ttf
IBMPlex/IBMPlexSans-Thin.ttf
IBMPlex/IBMPlexSans-ThinItalic.ttf
IBMPlex/IBMPlexSansCondensed-Bold.ttf
IBMPlex/IBMPlexSansCondensed-BoldItalic.ttf
IBMPlex/IBMPlexSansCondensed-ExtraLight.ttf
IBMPlex/IBMPlexSansCondensed-ExtraLightItalic.ttf
IBMPlex/IBMPlexSansCondensed-Light.ttf
IBMPlex/IBMPlexSansCondensed-LightItalic.ttf
IBMPlex/IBMPlexSansCondensed-Medium.ttf
IBMPlex/IBMPlexSansCondensed-MediumItalic.ttf
IBMPlex/IBMPlexSansCondensed-Regular.ttf
IBMPlex/IBMPlexSansCondensed-RegularItalic.ttf
IBMPlex/IBMPlexSansCondensed-SemiBold.ttf
IBMPlex/IBMPlexSansCondensed-SemiBoldItalic.ttf
IBMPlex/IBMPlexSansCondensed-Thin.ttf
IBMPlex/IBMPlexSansCondensed-ThinItalic.ttf
IBMPlex/IBMPlexSerif-Bold.ttf
IBMPlex/IBMPlexSerif-BoldItalic.ttf
IBMPlex/IBMPlexSerif-ExtraLight.ttf
IBMPlex/IBMPlexSerif-ExtraLightItalic.ttf
IBMPlex/IBMPlexSerif-Italic.ttf
IBMPlex/IBMPlexSerif-Light.ttf
IBMPlex/IBMPlexSerif-LightItalic.ttf
IBMPlex/IBMPlexSerif-Medium.ttf
IBMPlex/IBMPlexSerif-MediumItalic.ttf
IBMPlex/IBMPlexSerif-Regular.ttf
IBMPlex/IBMPlexSerif-SemiBold.ttf
IBMPlex/IBMPlexSerif-SemiBoldItalic.ttf
IBMPlex/IBMPlexSerif-Thin.ttf
IBMPlex/IBMPlexSerif-ThinItalic.ttf
Source/SourceCodePro-Black.ttf
Source/SourceCodePro-BlackItalic.ttf
Source/SourceCodePro-Bold.ttf
Source/SourceCodePro-BoldItalic.ttf
Source/SourceCodePro-ExtraBold.ttf
Source/SourceCodePro-ExtraBoldItalic.ttf
Source/SourceCodePro-ExtraLight.ttf
Source/SourceCodePro-ExtraLightItalic.ttf
Source/SourceCodePro-Italic.ttf
Source/SourceCodePro-Light.ttf
Source/SourceCodePro-LightItalic.ttf
Source/SourceCodePro-Medium.ttf
Source/SourceCodePro-MediumItalic.ttf
Source/SourceCodePro-Regular.ttf
Source/SourceCodePro-SemiBold.ttf
Source/SourceCodePro-SemiBoldItalic.ttf
Source/SourceSansPro-Black.ttf
Source/SourceSansPro-BlackItalic.ttf
Source/SourceSansPro-Bold.ttf
Source/SourceSansPro-BoldItalic.ttf
Source/SourceSansPro-ExtraLight.ttf
Source/SourceSansPro-ExtraLightItalic.ttf
Source/SourceSansPro-Italic.ttf
Source/SourceSansPro-Light.ttf
Source/SourceSansPro-LightItalic.ttf
Source/SourceSansPro-Regular.ttf
Source/SourceSansPro-SemiBold.ttf
Source/SourceSansPro-SemiBoldItalic.ttf
Source/SourceSerifPro-Black.ttf
Source/SourceSerifPro-BlackItalic.ttf
Source/SourceSerifPro-Bold.ttf
Source/SourceSerifPro-BoldItalic.ttf
Source/SourceSerifPro-ExtraLight.ttf
Source/SourceSerifPro-ExtraLightItalic.ttf
Source/SourceSerifPro-Italic.ttf
Source/SourceSerifPro-Light.ttf
Source/SourceSerifPro-LightItalic.ttf
Source/SourceSerifPro-Regular.ttf
Source/SourceSerifPro-SemiBold.ttf
Source/SourceSerifPro-SemiBoldItalic.ttf
fa-light-300.ttf
edunline.ttf
FXMatrix105MonoPicaRegular.otf)";
