#pragma once

const std::string installed_fonts = R"(IBMPlexMono-Bold.ttf
IBMPlexMono-BoldItalic.ttf
IBMPlexMono-ExtraLight.ttf
IBMPlexMono-ExtraLightItalic.ttf
IBMPlexMono-Italic.ttf
IBMPlexMono-Light.ttf
IBMPlexMono-LightItalic.ttf
IBMPlexMono-Medium.ttf
IBMPlexMono-MediumItalic.ttf
IBMPlexMono-Regular.ttf
IBMPlexMono-SemiBold.ttf
IBMPlexMono-SemiBoldItalic.ttf
IBMPlexMono-Thin.ttf 
IBMPlexMono-ThinItalic.ttf
IBMPlexSans-Bold.ttf
IBMPlexSans-BoldItalic.ttf
IBMPlexSans-ExtraLight.ttf
IBMPlexSans-ExtraLightItalic.ttf
IBMPlexSans-Italic.ttf
IBMPlexSans-Light.ttf
IBMPlexSans-LightItalic.ttf
IBMPlexSans-Medium.ttf
IBMPlexSans-MediumItalic.ttf
IBMPlexSans-Regular.ttf
IBMPlexSans-SemiBold.ttf
IBMPlexSans-SemiBoldItalic.ttf
IBMPlexSans-Thin.ttf
IBMPlexSans-ThinItalic.ttf
IBMPlexSerif-Bold.ttf
IBMPlexSerif-BoldItalic.ttf
IBMPlexSerif-ExtraLight.ttf
IBMPlexSerif-ExtraLightItalic.ttf
IBMPlexSerif-Italic.ttf
IBMPlexSerif-Light.ttf
IBMPlexSerif-LightItalic.ttf
IBMPlexSerif-Medium.ttf
IBMPlexSerif-MediumItalic.ttf
IBMPlexSerif-Regular.ttf
IBMPlexSerif-SemiBold.ttf
IBMPlexSerif-SemiBoldItalic.ttf
IBMPlexSerif-Thin.ttf
IBMPlexSerif-ThinItalic.ttf
SourceCodePro-Black.ttf
SourceCodePro-BlackItalic.ttf
SourceCodePro-Bold.ttf
SourceCodePro-BoldItalic.ttf
SourceCodePro-ExtraBold.ttf
SourceCodePro-ExtraBoldItalic.ttf
SourceCodePro-ExtraLight.ttf
SourceCodePro-ExtraLightItalic.ttf
SourceCodePro-Italic.ttf
SourceCodePro-Light.ttf
SourceCodePro-LightItalic.ttf
SourceCodePro-Medium.ttf
SourceCodePro-MediumItalic.ttf
SourceCodePro-Regular.ttf
SourceCodePro-SemiBold.ttf
SourceCodePro-SemiBoldItalic.ttf
SourceSansPro-Black.ttf
SourceSansPro-BlackItalic.ttf
SourceSansPro-Bold.ttf
SourceSansPro-BoldItalic.ttf
SourceSansPro-ExtraLight.ttf
SourceSansPro-ExtraLightItalic.ttf
SourceSansPro-Italic.ttf
SourceSansPro-Light.ttf
SourceSansPro-LightItalic.ttf
SourceSansPro-Regular.ttf
SourceSansPro-SemiBold.ttf
SourceSansPro-SemiBoldItalic.ttf
SourceSerifPro-Black.ttf
SourceSerifPro-BlackItalic.ttf
SourceSerifPro-Bold.ttf
SourceSerifPro-BoldItalic.ttf
SourceSerifPro-ExtraLight.ttf
SourceSerifPro-ExtraLightItalic.ttf
SourceSerifPro-Italic.ttf
SourceSerifPro-Light.ttf
SourceSerifPro-LightItalic.ttf
SourceSerifPro-Regular.ttf
SourceSerifPro-SemiBold.ttf
SourceSerifPro-SemiBoldItalic.ttf)";