#pragma once

const std::string installed_fonts = R"(IBMPlex/IBMPlexMono-Bold.ttf
IBMPlex/IBMPlexMono-BoldItalic.ttf
IBMPlex/IBMPlexMono-ExtraLight.ttf
IBMPlex/IBMPlexMono-ExtraLightItalic.ttf
IBMPlex/IBMPlexMono-Italic.ttf
IBMPlex/IBMPlexMono-Light.ttf
IBMPlex/IBMPlexMono-LightItalic.ttf
IBMPlex/IBMPlexMono-Medium.ttf
IBMPlex/IBMPlexMono-MediumItalic.ttf
IBMPlex/IBMPlexMono-Regular.ttf
IBMPlex/IBMPlexMono-SemiBold.ttf
IBMPlex/IBMPlexMono-SemiBoldItalic.ttf
IBMPlex/IBMPlexMono-Thin.ttf
IBMPlex/IBMPlexMono-ThinItalic.ttf
IBMPlex/IBMPlexSans-Bold.ttf
IBMPlex/IBMPlexSans-BoldItalic.ttf
IBMPlex/IBMPlexSans-ExtraLight.ttf
IBMPlex/IBMPlexSans-ExtraLightItalic.ttf
IBMPlex/IBMPlexSans-Italic.ttf
IBMPlex/IBMPlexSans-Light.ttf
IBMPlex/IBMPlexSans-LightItalic.ttf
IBMPlex/IBMPlexSans-Medium.ttf
IBMPlex/IBMPlexSans-MediumItalic.ttf
IBMPlex/IBMPlexSans-Regular.ttf
IBMPlex/IBMPlexSans-SemiBold.ttf
IBMPlex/IBMPlexSans-SemiBoldItalic.ttf
IBMPlex/IBMPlexSans-Thin.ttf
IBMPlex/IBMPlexSans-ThinItalic.ttf
IBMPlex/IBMPlexSerif-Bold.ttf
IBMPlex/IBMPlexSerif-BoldItalic.ttf
IBMPlex/IBMPlexSerif-ExtraLight.ttf
IBMPlex/IBMPlexSerif-ExtraLightItalic.ttf
IBMPlex/IBMPlexSerif-Italic.ttf
IBMPlex/IBMPlexSerif-Light.ttf
IBMPlex/IBMPlexSerif-LightItalic.ttf
IBMPlex/IBMPlexSerif-Medium.ttf
IBMPlex/IBMPlexSerif-MediumItalic.ttf
IBMPlex/IBMPlexSerif-Regular.ttf
IBMPlex/IBMPlexSerif-SemiBold.ttf
IBMPlex/IBMPlexSerif-SemiBoldItalic.ttf
IBMPlex/IBMPlexSerif-Thin.ttf
IBMPlex/IBMPlexSerif-ThinItalic.ttf
fa-light-300.ttf)";